url: "https://hsdecktracker.net"
baseurl: ""
permalink: pretty

vars:
  name: "Hearthstone Deck Tracker"
  description: "Deck and stats tracking for Hearthstone"
  logo: "/static/images/logo.png"
  email: "contact@hsdecktracker.net"
  google_analytics: "UA-68659282-1"

  links:
    github: HearthSim/Hearthstone-Deck-Tracker
    twitter: HSDeckTracker
    download: "https://github.com/HearthSim/HDT-Releases/releases/download/v1.0.4/HDT-Installer.exe"


# Syntax highlighting
markdown: kramdown
kramdown:
  # Use Github Flavored Markdown (including triple backticks)
  input: GFM
  hard_wrap: false  # No linebreak on newlines unless explicitly specified
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  # Reuse pygments syntax css class
    css_class: "highlight"

sass:
  style: :compressed


# Plug-ins
gems:
  - jekyll-mentions # @-mentions
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


exclude:
  - LICENSE
  - README.md
  - CNAME
